// Generates a binary file of raw wire-format messages that a peer simulator can
// replay to mock_r, standing in for the hand-captured input binaries the real
// DKM workflow uses.
//
// Output format is byte-identical to what mock_r's own MessageRecorder writes
// to input.bin: messages are simply concatenated, each one a raw MsgHeader
// followed by its payload, with no extra length prefix or delimiter (message
// boundaries come from msg_length, and the header carries the sender so a
// replayer can demux by link -- RSP=2, RSM=3, CRM=4, see ModuleId).
//
// Two modes:
//
//   default   A rotating-antenna scenario. The antenna sweeps in azimuth, each
//             beam is announced on RSM and immediately followed by an RSP
//             detection report holding whatever fell in that beam: real targets
//             with measurement noise, plus clutter. Targets move, some of them
//             turning, and each is also reported on CRM once per revolution as
//             a Prediction carrying its track_id. Gate and reporting areas are
//             re-announced periodically, and a jammer sits on a fixed bearing.
//             The result looks like a radar picture rather than a unit test.
//
//   --legacy  The original ten-message hand-built sequence. dkm-simulator's
//             checked-in input.bin was produced with it, and the gateway's
//             GroundTruthDecodeTest asserts against those exact values, so it
//             has to stay reproducible.
//
// Everything is deterministic for a given --seed, so a scenario can be
// regenerated byte-for-byte.

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <vector>

#include "interface/common.h"
#include "interface/crm.h"
#include "interface/def.h"
#include "interface/rsm.h"
#include "interface/rsp.h"

namespace
{

constexpr double kPi = 3.14159265358979323846;

struct Options
{
    std::string output       = "input.bin";
    double seconds           = 120.0;
    int targets              = 12;
    int beams_per_revolution = 90;
    int revolution_millis    = 2000;
    double max_range         = 2000.0;
    double clutter_per_beam  = 0.35;
    std::uint32_t seed       = 20260829u;
    bool legacy              = false;
    bool quiet               = false;
};

// Fills header.sender_id/receiver_id/msg_id/msg_length/timestamp the same way
// MessageChannel::send() does on the real peer side (mock_r is always the
// receiver, ModuleId::RDP), then appends the raw struct bytes to `out`.
template <typename T>
void write_msg(std::ofstream& out, T msg, ModuleId sender, std::size_t timestamp)
{
    msg.header.sender_id   = static_cast<std::size_t>(sender);
    msg.header.receiver_id = static_cast<std::size_t>(ModuleId::RDP);
    msg.header.msg_id      = T::kMsgId;
    msg.header.msg_length  = sizeof(T);
    msg.header.timestamp   = timestamp;
    out.write(reinterpret_cast<const char*>(&msg), sizeof(T));
}

// Wraps an angle into [0, 2*pi).
double wrap_angle(double radians)
{
    const double two_pi = 2.0 * kPi;
    radians = std::fmod(radians, two_pi);
    return radians < 0.0 ? radians + two_pi : radians;
}

// Smallest signed difference between two bearings, in [-pi, pi].
double angle_difference(double a, double b)
{
    double difference = wrap_angle(a) - wrap_angle(b);
    if (difference > kPi)
    {
        difference -= 2.0 * kPi;
    }
    else if (difference < -kPi)
    {
        difference += 2.0 * kPi;
    }
    return difference;
}

// One moving object. Position is integrated in Cartesian metres; the turn rate
// is what makes a track curve instead of drawing a straight line across the
// display, which is both more realistic and far more legible as a track.
struct Target
{
    std::size_t track_id = 0;
    double x             = 0.0;
    double y             = 0.0;
    double heading       = 0.0;  // direction of travel, radians
    double speed         = 0.0;  // m/s
    double turn_rate     = 0.0;  // radians/s
    double strength      = 1.0;  // scales detection probability

    void advance(double dt)
    {
        heading = wrap_angle(heading + turn_rate * dt);
        x += std::cos(heading) * speed * dt;
        y += std::sin(heading) * speed * dt;
    }

    double range() const { return std::hypot(x, y); }
    double bearing() const { return wrap_angle(std::atan2(y, x)); }
};

class Scenario
{
public:
    Scenario(const Options& options, std::mt19937& random) : options_(options), random_(random)
    {
        targets_.reserve(static_cast<std::size_t>(options.targets));
        for (int i = 0; i < options.targets; ++i)
        {
            targets_.push_back(spawn(/*from_edge=*/false));
        }
    }

    std::vector<Target>& targets() { return targets_; }

    // Puts a target somewhere plausible. `from_edge` is used when one leaves
    // coverage: it comes back in from the rim heading inwards, so a long
    // scenario keeps a populated picture instead of slowly emptying.
    //
    // Every spawn gets a fresh track number, never a recycled one. A tracker
    // that reused the id would have the display join the old track's last
    // position to the new one's first, drawing a chord straight across the
    // picture that no target ever flew.
    Target spawn(bool from_edge)
    {
        std::uniform_real_distribution<double> unit(0.0, 1.0);
        Target target;
        target.track_id = ++last_track_id_;

        const double bearing = unit(random_) * 2.0 * kPi;
        const double range = from_edge
                                 ? options_.max_range * 0.97
                                 : options_.max_range * (0.15 + 0.75 * unit(random_));
        target.x = std::cos(bearing) * range;
        target.y = std::sin(bearing) * range;

        // Inbound-ish so targets cross the coverage rather than skirting it.
        const double inbound = wrap_angle(bearing + kPi);
        target.heading   = wrap_angle(inbound + (unit(random_) - 0.5) * (from_edge ? 0.8 : 2.4));
        target.speed     = 40.0 + unit(random_) * 150.0;
        target.turn_rate = (unit(random_) - 0.5) * 0.06;
        target.strength  = 0.6 + unit(random_) * 0.6;
        return target;
    }

    void advance(double dt)
    {
        for (Target& target : targets_)
        {
            target.advance(dt);
            if (target.range() > options_.max_range * 1.02)
            {
                target = spawn(/*from_edge=*/true);
            }
        }
    }

private:
    const Options& options_;
    std::mt19937& random_;
    std::vector<Target> targets_;
    std::size_t last_track_id_ = 0;
};

// --- the legacy sequence -------------------------------------------------

// The original hand-built ten messages. Kept byte-for-byte so the checked-in
// input.bin and the tests that assert against it stay reproducible.
void write_legacy(std::ofstream& out)
{
    std::size_t timestamp = 1000;
    const auto next = [&timestamp]
    {
        const std::size_t value = timestamp;
        timestamp += 500;
        return value;
    };

    GateAreaMsg gate{};
    gate.start_distance = 500.0;
    gate.end_distance   = 600.0;
    gate.start_heading  = 1.0;
    gate.end_heading    = 1.2;
    write_msg(out, gate, ModuleId::RSM, next());

    ReportingAreaMsg reporting_area{};
    reporting_area.start_x = -1000.0;
    reporting_area.end_x   = 1000.0;
    reporting_area.start_y = -1000.0;
    reporting_area.end_y   = 1000.0;
    write_msg(out, reporting_area, ModuleId::RSM, next());

    ReadCommand read_command{};
    write_msg(out, read_command, ModuleId::RSM, next());

    // beam_type 0 -> processing averages all of this beam's detection inputs.
    BeamReport beam1{};
    beam1.beam_id        = 1;
    beam1.beam_timestamp = 2000;
    beam1.beam_type      = 0;
    beam1.beam_heading   = 0.5;
    write_msg(out, beam1, ModuleId::RSM, next());

    // beam_type 1 -> processing picks whichever detection input is closest to
    // the average, instead of averaging them.
    BeamReport beam2{};
    beam2.beam_id        = 2;
    beam2.beam_timestamp = 2100;
    beam2.beam_type      = 1;
    beam2.beam_heading   = 0.8;
    write_msg(out, beam2, ModuleId::RSM, next());

    DetectionReport det1{};
    det1.beam_id             = 1;
    det1.detection_timestamp = 2050;
    det1.detection_count     = 3;
    det1.detections[0]       = {90.0, 0.35};
    det1.detections[1]       = {100.0, 0.40};
    det1.detections[2]       = {110.0, 0.45};
    write_msg(out, det1, ModuleId::RSP, next());

    DetectionReport det2{};
    det2.beam_id             = 2;
    det2.detection_timestamp = 2150;
    det2.detection_count     = 3;
    det2.detections[0]       = {200.0, 0.75};
    det2.detections[1]       = {205.0, 0.80};
    det2.detections[2]       = {260.0, 0.95};
    write_msg(out, det2, ModuleId::RSP, next());

    // beam_id 99 was never announced via BeamReport, so processing should drop
    // this one (returns nullopt, no MeasurementReport out).
    DetectionReport det_unknown_beam{};
    det_unknown_beam.beam_id             = 99;
    det_unknown_beam.detection_timestamp = 2200;
    det_unknown_beam.detection_count     = 1;
    det_unknown_beam.detections[0]       = {50.0, 0.1};
    write_msg(out, det_unknown_beam, ModuleId::RSP, next());

    JammerReport jammer{};
    jammer.beam_id          = 1;
    jammer.jammer_timestamp = 2300;
    write_msg(out, jammer, ModuleId::RSP, next());

    Prediction prediction{};
    prediction.track_id = 1;
    prediction.distance = 150.0;
    prediction.heading  = 0.5;
    prediction.pos_x    = 130.0;
    prediction.pos_y    = 75.0;
    prediction.vel_x    = 1.5;
    prediction.vel_y    = -0.5;
    write_msg(out, prediction, ModuleId::CRM, next());
}

// --- the rotating-antenna scenario ---------------------------------------

struct Counts
{
    std::size_t beams        = 0;
    std::size_t detections   = 0;
    std::size_t detection_hits = 0;
    std::size_t predictions  = 0;
    std::size_t jammers      = 0;
    std::size_t areas        = 0;
    std::size_t reads        = 0;

    std::size_t total() const
    {
        return beams + detections + predictions + jammers + areas + reads;
    }
};

Counts write_scenario(std::ofstream& out, const Options& options)
{
    std::mt19937 random(options.seed);
    std::uniform_real_distribution<double> unit(0.0, 1.0);
    std::normal_distribution<double> noise(0.0, 1.0);

    Scenario scenario(options, random);
    Counts counts;

    const int beams = options.beams_per_revolution;
    const auto beam_count = static_cast<std::size_t>(beams);
    const double beam_width = 2.0 * kPi / static_cast<double>(beams);
    const double beam_millis =
        static_cast<double>(options.revolution_millis) / static_cast<double>(beams);
    const auto total_beams =
        static_cast<std::size_t>(options.seconds * 1000.0 / beam_millis);

    // Messages are laid out across the dwell they belong to, so the file reads
    // in strict global timestamp order the way a real capture does. The offsets
    // are fractions of the dwell rather than fixed milliseconds: a detection
    // report has to trail its beam report by a margin wide enough to survive
    // replay at speed, since the DKM receives the two on separate links and
    // silently drops a detection whose beam it has not heard about yet.
    const auto dwell_span = std::max<std::size_t>(1, static_cast<std::size_t>(beam_millis));
    constexpr double kAreasAt      = 0.00;
    constexpr double kBeamAt       = 0.10;
    constexpr double kDetectionAt  = 0.45;
    constexpr double kJammerAt     = 0.55;
    constexpr double kPredictionAt = 0.65;
    constexpr double kReadAt       = 0.95;

    // Two exclusion sectors the DKM suppresses measurements inside, and one
    // reporting rectangle everything has to fall within.
    const auto announce_areas = [&](const auto& at)
    {
        GateAreaMsg near_gate{};
        near_gate.start_distance = options.max_range * 0.24;
        near_gate.end_distance   = options.max_range * 0.33;
        near_gate.start_heading  = 0.85;
        near_gate.end_heading    = 1.35;
        write_msg(out, near_gate, ModuleId::RSM, at(kAreasAt));

        GateAreaMsg far_gate{};
        far_gate.start_distance = options.max_range * 0.62;
        far_gate.end_distance   = options.max_range * 0.78;
        far_gate.start_heading  = 3.55;
        far_gate.end_heading    = 4.30;
        write_msg(out, far_gate, ModuleId::RSM, at(kAreasAt));

        ReportingAreaMsg reporting{};
        reporting.start_x = -options.max_range;
        reporting.end_x   = options.max_range;
        reporting.start_y = -options.max_range;
        reporting.end_y   = options.max_range;
        write_msg(out, reporting, ModuleId::RSM, at(kAreasAt));

        counts.areas += 3;
    };

    // A jammer parked on one bearing, reported whenever the beam sweeps past.
    const double jammer_bearing = 5.10;

    std::vector<const Target*> in_beam;
    in_beam.reserve(static_cast<std::size_t>(std::max(options.targets, 1)));

    double previous_seconds = 0.0;

    for (std::size_t index = 0; index < total_beams; ++index)
    {
        const double now_seconds = static_cast<double>(index) * beam_millis / 1000.0;
        scenario.advance(now_seconds - previous_seconds);
        previous_seconds = now_seconds;

        // The dwell time, carried in every payload that reports on this beam.
        const auto dwell = static_cast<std::size_t>(now_seconds * 1000.0);
        const auto at = [&](double fraction)
        {
            const auto within =
                std::min(dwell_span - 1, static_cast<std::size_t>(beam_millis * fraction));
            return dwell + within;
        };

        const double bearing = wrap_angle(static_cast<double>(index) * beam_width);
        const std::size_t beam_id = index + 1;

        // The areas up front, then again every 20 revolutions so a replay
        // joined part-way through still knows about them.
        if (index % (beam_count * 20) == 0)
        {
            announce_areas(at);
        }

        BeamReport beam{};
        beam.beam_id        = beam_id;
        beam.beam_timestamp = dwell;
        // Alternating type exercises both of the DKM's reduction paths:
        // 0 averages the beam's detections, 1 picks the one nearest the average.
        beam.beam_type    = index % 2;
        beam.beam_heading = bearing;
        write_msg(out, beam, ModuleId::RSM, at(kBeamAt));
        counts.beams++;

        in_beam.clear();
        for (const Target& target : scenario.targets())
        {
            if (std::fabs(angle_difference(target.bearing(), bearing)) <= beam_width * 0.5)
            {
                in_beam.push_back(&target);
            }
        }

        // Everything the beam illuminated this dwell.
        DetectionReport report{};
        report.beam_id             = beam_id;
        report.detection_timestamp = dwell;
        std::size_t used = 0;

        for (const Target* target : in_beam)
        {
            if (used >= MAXIMUM_DETECTIONS_PER_BEAM)
            {
                break;
            }
            // Detection probability falls off with range, as it does on a real
            // set: a distant target is not seen on every sweep, which is what
            // makes a track look like a track rather than a solid line.
            const double range = target->range();
            const double probability =
                std::clamp(target->strength * (1.15 - range / options.max_range), 0.30, 0.97);
            if (unit(random) > probability)
            {
                continue;
            }

            const double range_noise   = 2.0 + range * 0.004;
            const double bearing_noise = 0.004;
            report.detections[used].distance = std::max(1.0, range + noise(random) * range_noise);
            report.detections[used].heading =
                wrap_angle(target->bearing() + noise(random) * bearing_noise);
            used++;
            counts.detection_hits++;

            // A strong close target sometimes splits into two returns.
            if (used < MAXIMUM_DETECTIONS_PER_BEAM && range < options.max_range * 0.35
                && unit(random) < 0.18)
            {
                report.detections[used].distance =
                    std::max(1.0, range + 6.0 + noise(random) * range_noise);
                report.detections[used].heading =
                    wrap_angle(target->bearing() + noise(random) * bearing_noise);
                used++;
                counts.detection_hits++;
            }
        }

        // Clutter: uncorrelated returns that no track will ever claim. Weighted
        // towards short range, where ground clutter actually lives.
        std::poisson_distribution<int> clutter(options.clutter_per_beam);
        const int clutter_count = clutter(random);
        for (int c = 0; c < clutter_count && used < MAXIMUM_DETECTIONS_PER_BEAM; ++c)
        {
            const double u = unit(random);
            report.detections[used].distance = options.max_range * (0.02 + 0.98 * u * u);
            report.detections[used].heading =
                wrap_angle(bearing + (unit(random) - 0.5) * beam_width);
            used++;
        }

        if (used > 0)
        {
            report.detection_count = used;
            write_msg(out, report, ModuleId::RSP, at(kDetectionAt));
            counts.detections++;
        }

        // The jammer, whenever the beam points at it.
        if (std::fabs(angle_difference(jammer_bearing, bearing)) <= beam_width * 0.5)
        {
            JammerReport jammer{};
            jammer.beam_id          = beam_id;
            jammer.jammer_timestamp = dwell;
            write_msg(out, jammer, ModuleId::RSP, at(kJammerAt));
            counts.jammers++;
        }

        // The tracker publishes a track when the antenna passes over it, so
        // predictions arrive spread through the revolution rather than in one
        // burst -- and each track is published exactly once per revolution.
        std::size_t published = 0;
        for (const Target* target : in_beam)
        {
            Prediction prediction{};
            prediction.track_id = target->track_id;
            prediction.distance = target->range();
            prediction.heading  = target->bearing();
            prediction.pos_x    = target->x;
            prediction.pos_y    = target->y;
            prediction.vel_x    = std::cos(target->heading) * target->speed;
            prediction.vel_y    = std::sin(target->heading) * target->speed;
            write_msg(out, prediction, ModuleId::CRM,
                      at(kPredictionAt + 0.02 * static_cast<double>(published)));
            published++;
            counts.predictions++;
        }

        // One read command per revolution, closing the sweep out.
        if (index % beam_count == beam_count - 1)
        {
            ReadCommand read_command{};
            write_msg(out, read_command, ModuleId::RSM, at(kReadAt));
            counts.reads++;
        }
    }

    return counts;
}

// --- command line --------------------------------------------------------

void usage(const char* program)
{
    std::cout
        << "Usage: " << program << " <output.bin> [options]\n"
        << "\n"
        << "  --seconds N      scenario length in seconds        (default 120)\n"
        << "  --targets N      moving targets                    (default 12)\n"
        << "  --beams N        beams per antenna revolution      (default 90)\n"
        << "  --revolution N   milliseconds per revolution       (default 2000)\n"
        << "  --range N        maximum range in metres           (default 2000)\n"
        << "  --clutter F      mean clutter returns per beam     (default 0.35)\n"
        << "  --seed N         PRNG seed, for reproducibility    (default 20260829)\n"
        << "  --legacy         write the original ten-message sequence instead\n"
        << "  --quiet          no summary on stdout\n";
}

enum class ParseResult
{
    ok,
    help,
    error
};

ParseResult parse(int argc, char** argv, Options& options)
{
    for (int i = 1; i < argc; ++i)
    {
        const std::string argument = argv[i];
        const auto value = [&](double& target) {
            if (i + 1 >= argc)
            {
                std::cerr << argument << " needs a value\n";
                return false;
            }
            target = std::stod(argv[++i]);
            return true;
        };

        if (argument == "--help" || argument == "-h")
        {
            usage(argv[0]);
            return ParseResult::help;
        }
        if (argument == "--legacy")
        {
            options.legacy = true;
        }
        else if (argument == "--quiet")
        {
            options.quiet = true;
        }
        else if (argument == "--seconds")
        {
            if (!value(options.seconds)) return ParseResult::error;
        }
        else if (argument == "--range")
        {
            if (!value(options.max_range)) return ParseResult::error;
        }
        else if (argument == "--clutter")
        {
            if (!value(options.clutter_per_beam)) return ParseResult::error;
        }
        else if (argument == "--targets" || argument == "--beams" || argument == "--revolution"
                 || argument == "--seed")
        {
            double numeric = 0;
            if (!value(numeric)) return ParseResult::error;
            if (argument == "--targets") options.targets = static_cast<int>(numeric);
            else if (argument == "--beams") options.beams_per_revolution = static_cast<int>(numeric);
            else if (argument == "--revolution") options.revolution_millis = static_cast<int>(numeric);
            else options.seed = static_cast<std::uint32_t>(numeric);
        }
        else if (!argument.empty() && argument[0] == '-')
        {
            std::cerr << "unknown option " << argument << "\n";
            usage(argv[0]);
            return ParseResult::error;
        }
        else
        {
            options.output = argument;
        }
    }

    if (options.targets < 0 || options.beams_per_revolution < 4 || options.revolution_millis < 10)
    {
        std::cerr << "targets must be >= 0, beams >= 4, revolution >= 10 ms\n";
        return ParseResult::error;
    }
    return ParseResult::ok;
}

}  // namespace

int main(int argc, char** argv)
{
    Options options;
    switch (parse(argc, argv, options))
    {
        case ParseResult::help: return 0;
        case ParseResult::error: return 1;
        case ParseResult::ok: break;
    }

    std::ofstream out(options.output, std::ios::binary | std::ios::trunc);
    if (!out)
    {
        std::cerr << "Failed to open " << options.output << " for writing\n";
        return 1;
    }

    if (options.legacy)
    {
        write_legacy(out);
        out.close();
        if (!options.quiet)
        {
            std::cout << "Wrote the legacy ten-message sequence to " << options.output << "\n";
        }
        return 0;
    }

    const Counts counts = write_scenario(out, options);
    out.close();

    if (!options.quiet)
    {
        const double revolutions =
            options.seconds * 1000.0 / static_cast<double>(options.revolution_millis);
        std::cout << "Wrote " << options.output << "\n"
                  << "  " << counts.total() << " messages over " << options.seconds << " s ("
                  << revolutions << " antenna revolutions)\n"
                  << "  " << counts.beams << " beam reports, " << counts.detections
                  << " detection reports carrying " << counts.detection_hits << " target returns\n"
                  << "  " << counts.predictions << " predictions from " << options.targets
                  << " concurrent targets, " << counts.jammers << " jammer reports, "
                  << counts.areas << " area definitions, " << counts.reads << " read commands\n"
                  << "  seed " << options.seed << ", reproducible byte for byte\n";
    }
    return 0;
}
